site_name: File Organization
site_description: A practical, logical guide to enhancing general file management. It covers concepts such as naming files and creating directories.
site_url: https://greentheblaze.github.io/file-organization/

repo_name: GreenTheBlaze/Roblox-Dev-Organization-Guide
repo_url: https://github.com/greentheblaze/file-organization

theme:
  name: material
  features:
    - navigation.footer
  palette:
      scheme: default
      primary: green
      accent: green

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.extra
  - attr_list

nav:
  - Home: index.md
  - Naming Conventions: naming-conventions.md